"use client";

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { CreditCard, Download, CheckCircle2, Clock, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useStudent } from '../layout';
import { useFirestore } from '@/firebase/provider';
import { collection, query, getDocs, where } from 'firebase/firestore';
import { useToast } from '@/hooks/use-toast';
import { downloadExcel } from '@/lib/excel';

export default function StudentFeesPage() {
  const student = useStudent();
  const firestore = useFirestore();
  const { toast } = useToast();

  const [fees, setFees] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (student) {
      fetchData();
    }
  }, [student, firestore]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const q = query(collection(firestore, 'fees'), where('studentId', '==', student?.id));
      const snap = await getDocs(q);
      const feesData = snap.docs.map(d => ({ id: d.id, ...(d.data() as any) }));
      
      // Sort by descending date
      setFees(feesData.sort((a,b) => new Date(b.dueDate).getTime() - new Date(a.dueDate).getTime()));
    } catch (err) {
      console.error(err);
      toast({ title: "Error", description: "Failed to load fee details.", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const downloadSlip = (fee: any) => {
    // We'll generate a simple layout for the slip using Excel utility for now
    const slipData = [{
      "Institution": "MPITI Saharanpur",
      "Slip Type": "Fee Payment Receipt/Status",
      "Student Name": student?.name,
      "Roll No": student?.rollNo,
      "Trade": student?.trade,
      "Fee Amount": "₹" + fee.amount,
      "Due Date": fee.dueDate,
      "Status": fee.status.toUpperCase()
    }];
    downloadExcel(slipData, `Fee_Slip_${fee.id}.xlsx`, 'Slip');
    toast({ title: "Downloaded", description: "Your fee slip has been downloaded." });
  };

  if (loading) return <div className="p-10 flex justify-center text-primary font-bold">Loading Fee Details...</div>;

  const totalDue = fees.filter(f => f.status !== 'paid').reduce((acc, curr) => acc + curr.amount, 0);

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-headline font-bold text-primary">Fee Details</h1>
          <p className="text-muted-foreground mt-1">View your payment history and download fee slips.</p>
        </div>
        <Card className="bg-primary text-primary-foreground border-none shadow-md px-6 py-4">
          <div className="text-sm font-semibold opacity-90">Total Outstanding Due</div>
          <div className="text-3xl font-bold flex items-center gap-2">₹{totalDue}</div>
        </Card>
      </div>

      <div className="grid gap-6">
        {fees.length === 0 ? (
          <div className="text-center p-12 bg-white rounded-lg border border-dashed border-slate-300">
             <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-4">
               <CreditCard className="w-8 h-8 text-slate-400" />
             </div>
             <h3 className="text-lg font-bold text-slate-600">No Fee Records Found</h3>
             <p className="text-sm text-slate-500">You currently have no fee demands generated by the administration.</p>
          </div>
        ) : (
          fees.map(f => (
             <Card key={f.id} className={`border shadow-sm transition-colors hover:border-primary/50 ${f.status === 'overdue' ? 'border-red-200 bg-red-50/10' : ''}`}>
               <CardContent className="p-6 flex flex-col md:flex-row gap-6 items-center justify-between">
                 <div className="flex gap-4 w-full md:w-auto">
                   <div className={`w-14 h-14 rounded-xl flex items-center justify-center shrink-0 ${
                     f.status === 'paid' ? 'bg-green-100 text-green-600' :
                     f.status === 'overdue' ? 'bg-red-100 text-red-600' :
                     'bg-amber-100 text-amber-600'
                   }`}>
                     {f.status === 'paid' ? <CheckCircle2 className="w-7 h-7" /> : 
                      f.status === 'overdue' ? <AlertCircle className="w-7 h-7" /> : 
                      <Clock className="w-7 h-7" />}
                   </div>
                   <div className="flex-1">
                     <h3 className="text-lg font-bold text-slate-800">Term/Session Fee</h3>
                     <p className="text-slate-500 text-sm">Due formatting: {f.dueDate}</p>
                     <div className="flex items-center gap-3 mt-2">
                        <span className={`text-xs font-bold px-2 py-0.5 rounded ${
                           f.status === 'paid' ? 'bg-green-100 text-green-700' :
                           f.status === 'overdue' ? 'bg-red-100 text-red-700 font-bold border border-red-200' :
                           'bg-amber-100 text-amber-700'
                        }`}>
                          {f.status.toUpperCase()}
                        </span>
                        {f.reminderSent && f.status !== 'paid' && (
                          <span className="text-xs font-bold px-2 py-0.5 bg-red-100 text-red-700 rounded animate-pulse">REMINDER ISSUED</span>
                        )}
                     </div>
                   </div>
                 </div>

                 <div className="flex items-center gap-6 w-full md:w-auto justify-between md:justify-end border-t border-slate-100 md:border-0 pt-4 md:pt-0">
                    <div className="text-right">
                      <div className="text-sm text-slate-500 font-semibold">Amount</div>
                      <div className="text-2xl font-bold text-slate-800">₹{f.amount}</div>
                    </div>
                    <Button onClick={() => downloadSlip(f)} variant="outline" className="gap-2 border-primary/20 hover:bg-primary/5">
                      <Download className="w-4 h-4" /> Slip
                    </Button>
                 </div>
               </CardContent>
             </Card>
          ))
        )}
      </div>
    </div>
  );
}
